BOUNDS_WIDTH: int = 800
MAX_X: float = BOUNDS_WIDTH / 2
MIN_X: float = -MAX_X
VIEW_WIDTH: int = BOUNDS_WIDTH + 20
M: 4
N: 4
WM: BOUNDS_WIDTH  

BOUNDS_HEIGHT: int = 800
MAX_Y: float = BOUNDS_HEIGHT / 2
MIN_Y: float = -MAX_Y
VIEW_HEIGHT: int = BOUNDS_HEIGHT + 20
WN: BOUNDS_HEIGHT 

CELL_RADIUS: int = 20
CELL_COUNT: int = 90
CELL_SPEED: float = 10.0 
